/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petable;

/**
 *
 * @author DELL
 */
public class Dog extends javax.swing.JFrame implements Pet {

    private String name;
    private int age;
    private String gender;
    private String healthStatus;
    private boolean isAdopted;

    public void createPet(String name, int age, String gender, String healthStatus, String petType) throws Exception {
         //implmentation for createPet (When DB is ready)
    }

    public void updatePet(int petId, String name, int age, String gender, String healthStatus) {
        this.name = name;
        this.age = age;
        this.gender = gender;
        this.healthStatus = healthStatus;
    }

    public void deletePet(int petId) {
        // Implementation for delete pet(When DB is ready)
    }

    public void adoptPet(int petId) {
        this.isAdopted = true;
    }

    public String displayPetDetails(int petId) {
        return "Name: " + this.name + ", Age: " + this.age + ", Gender: " + this.gender + ", Health status: " + this.healthStatus + ", Adoption status: " + (this.isAdopted ? "Adopted" : "Not adopted");
    }

    /**
     * Creates new form Dog
     */
    public Dog() {
        initComponents();
    }

    public Dog(String name, int age, String gender, String healthStatus, boolean isAdopted, String petType) throws Exception {
        if (!petType.toLowerCase().equals("dog")) {
            throw new Exception("Invalid pet type for dog");
        }
        this.name = name;
        this.age = age;
        this.gender = gender;
        this.healthStatus = healthStatus;
        this.isAdopted = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
