/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petable;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class GiveUp extends javax.swing.JFrame implements Service {

    /**
     * Creates new form GiveUp
     */
    private String petname;
    private int petage;
    private String gender;
    private String health;
     

    public GiveUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        PetName = new javax.swing.JTextField();
        PetAge = new javax.swing.JTextField();
        GenderF = new javax.swing.JRadioButton();
        GenderM = new javax.swing.JRadioButton();
        UnHealthy = new javax.swing.JRadioButton();
        Healthy = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(390, 844));

        PetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetNameActionPerformed(evt);
            }
        });

        GenderF.setText("jRadioButton1");
        GenderF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderFActionPerformed(evt);
            }
        });

        GenderM.setText("jRadioButton2");

        UnHealthy.setText("jRadioButton3");
        UnHealthy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnHealthyActionPerformed(evt);
            }
        });

        Healthy.setText("jRadioButton4");
        Healthy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthyActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(Healthy)
                        .addGap(29, 29, 29)
                        .addComponent(UnHealthy))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GenderM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenderF)))
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PetName, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(PetAge))
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(PetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(PetAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderF)
                    .addComponent(GenderM))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnHealthy)
                    .addComponent(Healthy))
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetNameActionPerformed

    private void GenderFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderFActionPerformed

    private void UnHealthyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnHealthyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnHealthyActionPerformed

    private void HealthyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HealthyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String errorMessage="";
        
        petname = PetName.getText();
        if (petname == null || petname.isEmpty()) {
            errorMessage += "Please enter the pet's name.";
            //JOptionPane.showMessageDialog(this,  errorMessage,"Invalid input", JOptionPane.ERROR_MESSAGE);

        }
        String ageString = PetAge.getText();
        if (ageString.isEmpty()) {

            errorMessage += "\nPlease enter the pet's age.";

        }
        try {
            petage = Integer.parseInt(ageString);
        } catch (NumberFormatException e) {
            errorMessage += "\nPlease enter a valid age (an integer).";

        }
        if (!GenderF.isSelected() && !GenderM.isSelected()) {
            errorMessage += "\nPlease select the pet's gender.";

        }
        gender = GenderF.isSelected() ? "Female" : "Male";
        if (!Healthy.isSelected() && !UnHealthy.isSelected()) {
            errorMessage += "\nPlease select the pet's health condition.";
            JOptionPane.showMessageDialog(this, errorMessage, "Invalid input", JOptionPane.ERROR_MESSAGE);

            return;
        }
        health = Healthy.isSelected() ? "Healthy" : "Unhealthy";

        // If all fields are valid, do something with the data, e.g. call a method on a service object
        // service.submit(petname, petage, gender, health);
        new User().setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiveUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GenderF;
    private javax.swing.JRadioButton GenderM;
    private javax.swing.JRadioButton Healthy;
    private javax.swing.JTextField PetAge;
    private javax.swing.JTextField PetName;
    private javax.swing.JRadioButton UnHealthy;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
